name: Build and Upload Github Release

on:
   push:
      tags:
         - 'v**'

   # Allow running manually from the actions tab
   workflow_dispatch:

concurrency:
   group: "release"
   cancel-in-progress: true

jobs:
   create-release:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         -  name: Generate Release Notes
            run: bash ./.github/generate-release-notes.sh ${{ github.ref_name }} | tee RELEASE_NOTES.md

         -  name: Archive Release
            run: |
               zip -r 5etools-${{ github.ref_name }}.zip . -x '*.git*' '*node_modules*' '*.github*'

         -  name: Upload Release
            run: |
               gh release create "${{github.ref_name}}" --title "${{github.ref_name}}" --notes-file RELEASE_NOTES.md 5etools-${{ github.ref_name }}.zip
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
