name: Reapply My Custom Changes After Sync

on:
  push:
    branches:
      - main  # Detects Pull app sync to main branch

jobs:
  reapply-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git
      run: |
        git config --global user.email "orcnog@gmail.com"
        git config --global user.name "orcnog"

    - name: Check out custom changes branch
      run: git checkout orcnog

    - name: Attempt to rebase custom changes
      run: |
        git rebase main || git rebase --abort

    - name: Push changes back to custom branch (if rebase was successful)
      if: success()
      run: git push origin orcnog --force-with-lease

    - name: Send failure email if rebase fails
      if: failure()
      run: |
        echo "Rebase failed due to conflicts. Please resolve manually." | mail -s "GitHub Action: Rebase Failure" orcnog@gmail.com
