name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 5etools-mirror-3 repo
        uses: actions/checkout@v3
        with:
          repository: orcnog/5etools-mirror-3
          ref: main

      - name: Add upstream
        run: git remote add upstream https://github.com/5etools-mirror-3/5etools-2014-src.git # The original repo URL (the fork source)

      - name: Fetch upstream
        run: git fetch upstream

      - name: Set committer identity
        run: |
          git config --global user.email "orcnog@gmail.com" # Use my email
          git config --global user.name "orcnog" # Use my name

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin main

      - name: Add secondary remote (orcnog.github.io repo)
        run: git remote add secondary https://github.com/orcnog/orcnog.github.io.git

      - name: Checkout or create 5etools-mirror-3 branch
        run: |
          git fetch secondary
          git checkout 5etools-mirror-3 || git checkout -b 5etools-mirror-3
          git reset --hard origin/main # Sync it with the latest main branch
      
      - name: Set up Git credentials
        run: |
          git config credential.helper store
          echo "https://orcnog:${{ secrets.ACTIONS_PAT }}@github.com" > ~/.git-credentials

      - name: Push changes to 5etools-mirror-3 branch in orcnog.github.io repo
        run: |
          git push secondary 5etools-mirror-3 --force

